[tool.poetry]
name = "mmf-analyzer"
version = "0.1.0"
description = ""
authors = ["Muniu Kariuki <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
